# 各固有名詞について、その特徴をwikiページから抽出する。

In [ ]:
import pandas as pd
import json
import re
import os
import sys
from tqdm import tqdm
import wikipediaapi
from dotenv import load_dotenv


# プロジェクトのutils追加
project_root = os.path.join(os.getcwd(), "..")
sys.path.append(project_root)


load_dotenv() # API keyの読み込み

# from openai import OpenAI
# client = OpenAI()

# gptは少し高いのでgeminiに変更。wikiからの特徴抽出タスクは複雑な思考を必要としないため、軽量のモデルで十分と判断。
from google import genai
client = genai.Client()

## 固有名詞読み込み

In [ ]:

delete_list = ["year", "Election"] # year は、すべて2001, 2020, 2231 のような年の数字のみだったため削除。Electionも実体ではない

whole_df = pd.DataFrame()
for filename in os.listdir(os.path.join(project_root, "data", "dbpedia", "wikidata_Things_childs_LIMIT1000")):
    if filename.replace(".csv", "") in delete_list:
        # 削除対象のカテゴリは読み込まない
        continue
    if filename.endswith(".csv"):
        df = pd.read_csv(os.path.join(project_root, "data", "dbpedia", "wikidata_Things_childs_LIMIT1000", filename))
        whole_df = pd.concat([whole_df, df], ignore_index=True)
print(f"Total proper nouns collected: {len(whole_df)}")
whole_df.head()

Total proper nouns collected: 158013

,qid,label,class_label,class_qid
0,Q137919338,Colombian National Cross-Country Skiing,swimmer,Q10843402
1,Q12512,St. Peter's Basilica,church,Q16970
2,Q48435,Basilica and Expiatory Church of the Holy Family,church,Q16970
3,Q5933,Westminster Abbey,church,Q16970
4,Q2943,Sistine Chapel,church,Q16970

### 複数行に同じlabelがある場合は、そのlabelの行を削除する
- subclassのsubclassを取っているものもあるため、上位のsubclassとその下位のsubclassの両方に同じ固有名詞が属している心配がある。

In [3]:
# 複数行に同じlabelがある場合は、そのlabelの行を削除する
# whole_filtered_df 
whole_df = whole_df.drop_duplicates(subset=['label'], keep=False)
# print(f"Total proper nouns after removing duplicates: {len(whole_filtered_df)}")
print(f"Total proper nouns after removing duplicates: {len(whole_df)}")

Total proper nouns after removing duplicates: 123174

### 属する固有名詞が一定数以上ある中カテゴリを、実験対象として選ぶ

In [4]:
# 中カテゴリごとの固有名詞の数をカウントし、dfにする
category_count_df = whole_df.groupby("class_label").size().reset_index(name="count")
category_count_df

      class_label  count
0       Algorithm    419
1         Archive    366
2            Band    939
3     Biomolecule      7
4           Chief      5
..            ...    ...
234        weapon    262
235          wine    168
236        winery    623
237  written work    909
238           zoo    331

[239 rows x 2 columns]

In [5]:
# propnoun_num_threshold 以上の固有名詞があるカテゴリを抽出する
# propnoun_num_threshold = 200 # 150
propnoun_num_for_init_vec = 100 # 1カテゴリあたりで、初期化vec(平均vec)の作成に使う概念数
propnoun_num_for_new_concept = 50 # 1カテゴリあたりで、新規概念の元にする概念数
propnoun_num_threshold = propnoun_num_for_init_vec + propnoun_num_for_new_concept
filtered_category_count_df = category_count_df[category_count_df["count"] >= propnoun_num_threshold]
print(f"{propnoun_num_threshold}以上の固有名詞があるカテゴリの数: {filtered_category_count_df.shape[0]}")
filtered_category_count_df

150以上の固有名詞があるカテゴリの数: 159

          class_label  count
0           Algorithm    419
1             Archive    366
2                Band    939
9                Food    985
11   Intercommunality    558
..                ...    ...
234            weapon    262
235              wine    168
236            winery    623
237      written work    909
238               zoo    331

[159 rows x 2 columns]

### 大体のコストを試算

In [6]:
prompt_text_path = os.path.join(project_root, "data", "prompt", "baseprompt_of_gen_wiki_fact_extraction.txt")
with open(prompt_text_path, "r", encoding="utf-8") as f:
    gen_triplet_prompt_base = f.read()
print(len(gen_triplet_prompt_base.split())*1.5+400, "tokens in the base prompt for generating factual feature sentences") # 単語がsubtokenに分かれることで大体1.5倍くらいに増えると考えて想定

1286.5 tokens in the base prompt for generating factual feature sentences

In [ ]:

# gpt-5-miniの場合:
# cost = (0.25 / 1000000 * 1228.0 + 2 / 1000000 *4000) * 50 * 160
# gemini-2.5-flash-lightの場合:
cost = (0.1 / 1000000 * 1228.0 + 0.4 / 1000000 * 4000) * 50 * 160
print(f"Estimated cost for generating factual feature sentences for {propnoun_num_for_init_vec} categories, and each category has {propnoun_num_for_new_concept} concepts in one category: ${cost:.4f}")

Estimated cost for generating factual feature sentences for 100 categories, and each category has 50 concepts in one category: $13.7824

In [38]:
target_categories = filtered_category_count_df["class_label"].tolist()
print("=== Target categories for generating factual feature sentences ===")
print(target_categories)

=== Target categories for generating factual feature sentences ===
['Algorithm', 'Archive', 'Band', 'Food', 'Intercommunality', 'Legal Case', 'Medicine', 'Noble family', 'Painting', 'Port', 'Site of Special Scientific Interest', 'Wikimedia template', 'Windmill', 'academic subject', 'activity', 'agent', 'aircraft', 'airline', 'airport', 'album', 'anatomical structure', 'animal', 'archipelago', 'artery', 'artwork', 'asteroid', 'award', 'board game', 'book', 'bridge', 'broadcast network', 'broadcaster', 'brown dwarf', 'building', 'card game', 'casino', 'castle', 'cave', 'cemetery', 'church', 'city', 'company', 'contest', 'cycling race', 'dam', 'deity', 'drama', 'drug', 'educational institution', 'event', 'factory', 'family', 'fictional character', 'film festival', 'galaxy', 'game', 'garden', 'given name', 'glacier', 'golf course', 'government agency', 'handball team', 'historical period', 'hockey team', 'hot spring', 'hotel', 'identifier', 'ideology', 'island', 'lake', 'language', 'law firm', 'legislature', 'letter', 'library', 'lighthouse', 'locality', 'locomotive', 'lunar crater', 'magazine', 'manga', 'meeting', 'military unit', 'mineral', 'monastery', 'monument', 'motorcycle', 'mountain', 'mountain pass', 'mountain range', 'movie', 'museum', 'music festival', 'music genre', 'musical work', 'name', 'natural region', 'newspaper', 'organisation', 'parliament', 'planet', 'plant', 'play', 'poem', 'political party', 'power station', 'prefecture', 'prison', 'profession', 'programming language', 'protected area', 'protein', 'railway line', 'record label', 'research project', 'restaurant', 'river', 'road', 'school', 'ship', 'shopping mall', 'shrine', 'ski resort', 'skyscraper', 'soccer club', 'software', 'solar eclipse', 'space mission', 'spacecraft', 'sport', 'sports league', 'sports team', 'square', 'state', 'stream', 'street', 'subway station', 'synagogue', 'taxonomic group', 'television show', 'tennis tournament', 'term of office', 'theatre', 'tournament', 'tower', 'town', 'trade union', 'train', 'train station', 'university', 'valley', 'vein', 'video game', 'volcano', 'weapon', 'wine', 'winery', 'written work', 'zoo']

In [58]:
i = 10
print(target_categories[i])
concepts = whole_df[whole_df["class_label"] == target_categories[i]]["label"].tolist()
print(f"=== Example concepts in the category '{target_categories[i]}' ===")
print(concepts)

Site of Special Scientific Interest
=== Example concepts in the category 'Site of Special Scientific Interest' ===

In [42]:
t = """
In 1958, municipal associations on both sides of the border organised the first cross-border conference. An association on the German side, the ‘Interessensgemeinschaft Rhein-Ems’, had been founded as an intermunicipal interest association in 1954 by representatives of local business and local authority politicians of the Westmünsterland and the Grafschaft Bentheim and Lingen Kreise. Among its objectives were the improvement of the local and regional infrastructures, which, in the eyes of the local elites, deserved more attention on the part of the Land and federal governments. On the Dutch side of the border, this was followed by the establishment of its own inter-municipal association.

In 1962, the more informal Interessensgemeinschaft was replaced by the ‘Kommunalgemeinschaft Weser-Ems’, a public law intermunicipal body. A similar process of intermunicipal integration occurred in the adjoining Dutch border area where the municipalities in the areas of Twente and Gelderland founded the Belangengemeenschap Twente-Gelderland (later Samenwerkingsverband Twente, today Regio Twente) with the explicit objective of co-operating more closely with the Interessensgemeinschaft Rhein-Ems (later Kommunalgemeinschaft Rhein-Ems). Subsequently, a second association, the Samenwerkingsverband Oost-Gelderland (today Regio Achterhoek), was established in the Dutch border area. Today, the Kommunalgemeinschaft Rhein-Ems, the Regio Twente and the Regio Achterhoek together form the EUREGIO.

The EUREGIO Arbeitsgruppe (‘work group’) was founded in 1966 to operate as the informal board of the cross-border region. On the basis of regular meetings, it attempted to shift the EUREGIO’s work from purely project-based contacts towards a programmatic collaboration.

An important event was the establishment of the Alfred-Mozer-Kommission in 1970, responsible for cross-border initiatives in the cultural field. At the same time, a secretariat was established comprising two units on each side of the border and funded by membership fees. Two studies, in the fields of culture and economic affairs respectively, gave the secretariats a programmatic basis for the further development of the EUREGIO.

In the mid-seventies, the Arbeitsgruppe was given a formal basis by means of a statute (Satzung), and a common action programme was developed. This institutionalisation process ended with the Euregio-Rat in 1978, the first cross-border regional parliamentary assembly in Europe constituted by the political delegates of the member authorities.

In 1985, the separate secretariats were merged into a single Geschäftsstelle, located in Gronau (DE), situated 75m from the border, employing both Dutch and German staff. On the programmatic side, a ‘regional cross-border action programme’ was presented in 1987, outlining the general strategy for the EUREGIO for a twenty-year period (NEI nd). The elaboration of the programme was based on an agreement in 1984 between the German Federal ministry of economics, the Dutch ministry of economics and the German states of North Rhine-Westphalia and Lower Saxony. Funding was also provided by the European Commission. A steering committee was established, involving the partners in this agreement as well as the provinces, Bezirksregierungen and the EUREGIO. The action programme contained an economic and social analysis of the programme areas, and listed a series of measures aimed at promoting their socio-economic development.

This action programme constituted the main input for the first OP for the period 1989-1992, funded as pilot project under art. 10 ERDF. When the European Commission launched Interreg I in 1990, the EUREGIO reacted with the speedy elaboration of a second OP based on its accumulated experience."""

print(len(t.split()))

541

In [59]:
t = """
The Angle Peninsula Coast on the southern side of the entrance to the Milford Haven Waterway in Pembrokeshire, Wales, is a Site of Special Scientific Interest.[1] There is a wide range of wildlife and a former Royal Air Force station.


Remains of gun emplacements
The peninsula is rich in Second World War defences and the site of the former air base RAF Angle. The hollows in the banks around it were used to house machine guns in the Second World War and there was a searchlight battery here. Inland from East Picket bay are the remnants of the E-Pens used to house fighter aircraft if they were needed. In a field close to the World War I memorial there are the remains of an anti-aircraft post. On a section of the coastal path just past the RNLI lifeboat house there are visible remains of an anti-aircraft post. This site was later changed and used to house a 40 mm Rolls-Royce cannon. At the north hill, there are remains of a Laing hut that was used as housing for a searchlight. On a rocky patch of ground at west pill is a brick mine watcher hut. This was used specifically to watch out for the enemy who may be laying mines in Milford Haven.

RAF Angle was an airfield during World War II. It opened in 1941 after Luftwaffe attacks against Pembroke Dock. The airfield, which began as a station for No. 10 Group, Fighter Command, housed several squadrons during the war such as No. 312 (Czechoslovak) Squadron RAF and the Canadian 412 Transport Squadron. Planes included Supermarine Spitfires, Westland Whirlwinds and Hawker Hurricanes. In 1943 operational control passed on to the Fleet Air Arm of the Royal Navy. During this time a Sunderland flying boat landed at Angle airfield after receiving hull damage during a rescue. It returned to the RAF and became home to the Coastal command unit who tested weapons that could be used against German U-boats. After the war was over the buildings were no longer used and many were removed in the 1980s; however, some still stand in remote locations.

On 15 February 1996, the oil tanker Sea Empress grounded at the Milford Haven Waterway entrance, spilling 72,000 tonnes of crude oil. The coastline around Angle was severely damaged. The effect of the oil spill lasted several years and cost £60 million.[2]
"""
print(len(t.split()))

396

## wikiから特徴抽出
- 各カテゴリあたり、固有名詞50個について特徴を抽出する。
- まずカテゴリ毎に固有名詞をシャッフルする。
- そして、最初の固有名詞から順番に特徴を抽出していく。
- 特徴が60個取れなかった固有名詞は捨て、次の固有名詞に移る。
- これを繰り返し、特徴が60個取れた固有名詞を50個集める。
- 固有名詞が50個集まった時点で、そのカテゴリの特徴抽出は終了とする。

In [7]:

# 保存先
gen_result_savedir = os.path.join(project_root, "data", "generated_facts_in_wiki")
os.makedirs(gen_result_savedir, exist_ok=True)


print_results = True  # get_concept_list_with_complete_cos_similar_termsの結果を表示するかどうか


def fetch_wikipedia_page(title: str, lang: str = "en") -> dict:
    """Fetch a Wikipedia page by title and language.
    wiki pageを取得する．
    Args:
        title (str): Wikipediaページのタイトル
        lang (str): Wikipediaの言語コード（例: "en", "ja"）

    Returns:
        dict: ページ情報を含む辞書．ページが存在しない場合は'exists'キーがFalseとなる．

    Note:
        * titleに完全一致するページのみが取得されるため，google検索のように最も近いが異なるものを検索結果として返すことはない．
        * そのため，提示した固有名詞とは違う情報のページが返されることは無い．
        * また，titleの綴りが間違っていても, userがよく間違う綴りの場合は, wikipedia側で正しいページにリダイレクトしてくれる．
            * 例: "Colloseum" -> "Colosseum"のページを取得
    
    """
    wiki = wikipediaapi.Wikipedia(
        user_agent="my-wikipedia-fetcher/1.0 (contact: your_email@example.com)",
        language=lang,
    )
    page = wiki.page(title)

    if not page.exists():
        return {"exists": False, "title": title, "lang": lang}

    return {
        "exists": True,
        "title": page.title,
        "url": page.fullurl,
        "summary": page.summary,
        "text": page.text,  # 全文（長いので注意）
    }


def extract_wiki_main_text(text: str) -> str:
    """Wikipediaページの情報から本文テキストのみを抽出する。
    Args:
        text (str): Wikipediaページの全文

    Returns:
        str: Wikipediaページの本文テキスト。ページが存在しない場合は空文字列を返す。
    """

    STOP_SECTIONS = {
        "see also",
        "references",
        "notes",
        "further reading",
        "external links",
        "bibliography",
        "sources",
        "works cited",
        "citations",
    }
    # 見出し候補を | で連結
    titles = "|".join(re.escape(x) for x in STOP_SECTIONS)

    # 行頭に単独で出る見出しを検出
    # 例:
    # See also
    # References
    #
    # または wiki風:
    # == See also ==
    pattern = rf"(?mi)^\s*(?:=+\s*)?(?:{titles})(?:\s*=+)?\s*$"

    # 最初に見つかった見出し以降を全て削除
    m = re.search(pattern, text)
    if m:
        text = text[:m.start()]

    # 脚注番号 [1], [23] を削除
    text = re.sub(r"\[\d+\]", "", text)

    # 空行を整理
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text

In [ ]:
"""
作成日: 2025/12/25

wiki記事から, 固有名詞に特有の特徴を, 指定した形式に沿って抽出する
* ただし, 抽出した特徴文はそのまま保存し, 後で解析する.
* また, wikipageを取得したconceptのみに対して生成を実行. wikipageは，cossimが-0.2~0.9まで全て揃っているconceptのみを対象に収集しているため.

この生成にかかるコスト概算:
* 入力promptは520tokens, 出力は1300tokens程度と想定.
* 対象concept数は57->60件と想定
* json形式の指定は省略
* (0.25 / 1000000 *520 + 2 / 1000000 *1300) * 60 = 約0.16ドル. 激安!

Usage:
    nohup uv run python src/gen_factual_feature_sentences_from_wiki.py > gen_factual_feature_sentences_from_wiki.log 2>&1 &
"""

print("=== Generating factual feature sentences from Wikipedia articles ===")


# *** 準備 ***
# prompt と jsonschema を読み込み
print("Preparing prompts and schemas...")
print("Preparing prompts and schemas...")
prompt_schema_path = os.path.join(project_root, "data", "prompt", "baseprompt_of_gen_wiki_fact_extraction_for_googleai.json")
prompt_text_path = os.path.join(project_root, "data", "prompt", "baseprompt_of_gen_wiki_fact_extraction.txt")


with open(prompt_schema_path, "r", encoding="utf-8") as f:
    schema = json.load(f)
with open(prompt_text_path, "r", encoding="utf-8") as f:
    gen_triplet_prompt_base = f.read()

=== Generating factual feature sentences from Wikipedia articles ===
Preparing prompts and schemas...
Preparing prompts and schemas...
Checking already generated concepts...

### お試し生成

In [9]:
# wikipageを取得する
wiki_word_num_threshold = 500 # 十分な情報量のあるwikipageに対してのみ生成を行う

target_categories = filtered_category_count_df["class_label"].tolist()
print("=== Target categories for generating factual feature sentences ===")
print(target_categories)

=== Target categories for generating factual feature sentences ===
['Algorithm', 'Archive', 'Band', 'Food', 'Intercommunality', 'Legal Case', 'Medicine', 'Noble family', 'Painting', 'Port', 'Site of Special Scientific Interest', 'Wikimedia template', 'Windmill', 'academic subject', 'activity', 'agent', 'aircraft', 'airline', 'airport', 'album', 'anatomical structure', 'animal', 'archipelago', 'artery', 'artwork', 'asteroid', 'award', 'board game', 'book', 'bridge', 'broadcast network', 'broadcaster', 'brown dwarf', 'building', 'card game', 'casino', 'castle', 'cave', 'cemetery', 'church', 'city', 'company', 'contest', 'cycling race', 'dam', 'deity', 'drama', 'drug', 'educational institution', 'event', 'factory', 'family', 'fictional character', 'film festival', 'galaxy', 'game', 'garden', 'given name', 'glacier', 'golf course', 'government agency', 'handball team', 'historical period', 'hockey team', 'hot spring', 'hotel', 'identifier', 'ideology', 'island', 'lake', 'language', 'law firm', 'legislature', 'letter', 'library', 'lighthouse', 'locality', 'locomotive', 'lunar crater', 'magazine', 'manga', 'meeting', 'military unit', 'mineral', 'monastery', 'monument', 'motorcycle', 'mountain', 'mountain pass', 'mountain range', 'movie', 'museum', 'music festival', 'music genre', 'musical work', 'name', 'natural region', 'newspaper', 'organisation', 'parliament', 'planet', 'plant', 'play', 'poem', 'political party', 'power station', 'prefecture', 'prison', 'profession', 'programming language', 'protected area', 'protein', 'railway line', 'record label', 'research project', 'restaurant', 'river', 'road', 'school', 'ship', 'shopping mall', 'shrine', 'ski resort', 'skyscraper', 'soccer club', 'software', 'solar eclipse', 'space mission', 'spacecraft', 'sport', 'sports league', 'sports team', 'square', 'state', 'stream', 'street', 'subway station', 'synagogue', 'taxonomic group', 'television show', 'tennis tournament', 'term of office', 'theatre', 'tournament', 'tower', 'town', 'trade union', 'train', 'train station', 'university', 'valley', 'vein', 'video game', 'volcano', 'weapon', 'wine', 'winery', 'written work', 'zoo']

In [10]:

i = 8
print(target_categories[i])
concepts = whole_df[whole_df["class_label"] == target_categories[i]]["label"].tolist()
print(f"=== Example concepts in the category '{target_categories[i]}' ===")
print(concepts)

Painting
=== Example concepts in the category 'Painting' ===
['Madonna of Kyiv', 'Black Madonna of Częstochowa', 'My God, Help Me to Survive This Deadly Love', 'Rock Paintings of Hua Mountain', 'Along the River During the Qingming Festival', 'Our Lady of Kazan', 'The Battle of Anghiari', 'Our Lady of Perpetual Help', 'Trinity icon', 'Trojeručica', 'Balloon Girl', 'Christ Pantocrator (Sinai)', 'Leda and the Swan', 'Panagia Portaitissa', 'Madonna of the Yarnwinder', 'Wall of Love', 'Blue Dancers', 'Young Hare', 'Arrival of the Hungarians', 'Pornocrates', 'Portrait of a Young Man', 'San Damiano cross', 'Cestello Annunciation', 'The Chocolate Girl', 'Our Lady of Smolensk', 'Madonna and Child Enthroned with Angels and Prophets. ˋSanta Trinità Maestà´', 'Death playing chess', 'Beethoven Frieze', 'Great Piece of Turf', 'Agiosoritissa', 'Madonna Bardi', 'Theotokos of Tikhvin', 'Duria Antiquior', 'Saint Sebastian', 'Theotokos of Pochayiv', 'Manoppello Image', 'The Annunciation', 'Wing of a European Roller', 'Our Lady of the Don', 'Lamentation over the Dead Christ', 'Blachernitissa', 'Investiture of Zimrilim', 'Cambrai Madonna', 'Our Lady of Budslau', 'Ustyug Annunciation', 'Lamentation over the Dead Christ with Saints', 'Saint Augustine', 'The History of Mexico', 'Christ and Abbot Mena', 'Theotokos Fyodorovskaya', 'Kursk Root Icon of the Sign', 'Presencia de America Latina', 'Nicopeia', 'The Angel with Golden Hair', 'Horses in landscape', 'Our Lady Derzhavnaya', 'The Son of a Migrant from Syria', 'Boy Cutting Grass with a Sickle', 'The Reaper', 'Karin by the shore', 'Last Supper', 'Archaeological site Serranía La Lindosa', 'Theotokos of Bogolyubovo', "Sant'Ambrogio Altarpiece", 'The Apparition', 'Thongdrel', 'Gua Tambun', 'Summer Fun', 'Our Lady of Sorrows, Queen of Poland', 'Our Lady of Šiluva', 'Arab Woman', 'Adoration of the Kings', 'The Merciful Knight', 'Scrovegni Crucifix by Giotto', 'Crucifix by Cimabue, Santa Croce', 'Miró Wall', 'Hanoi Ceramic Mosaic Mural', 'Eidophusikon', 'Drawbridge in Nieuw-Amsterdam', 'Half-Length Nude with Hat', 'The Queen stands at your right hand', 'Venus and the Three Graces Presenting Gifts to Giovanna degli Albizzi', 'Man at the Crossroads', 'Khakhuli triptych', 'Well Hung Lover', "The 'Laakmolen' near The Hague", 'Court Ladies Preparing Newly Woven Silk', 'Altarpiece of the church of the monastery of Santo Domingo el Antiguo', 'The Mother of God of Trakai', 'The Painter on His Way to Work', 'Inexhaustible Chalice', 'The Rope Dancer', 'Crucifix by Cimabue, San Domenico (Arezzo)', 'West Bank Wall graffiti art', 'Blessed Be the Host of the King of Heaven', 'Slave Labour', 'The Great Wall of Los Angeles', 'The Holy Infants Embracing', 'Ancha icon', 'Tuttomondo', 'Saint Julian and the Redeemer', 'Presentation at the Temple', 'Les Choristes', 'Mareorama', 'A Young Man Being Introduced to the Seven Liberal Arts', 'Battle of the Novgorodians with the Suzdalians', 'Star of Bethlehem', 'Emperor Jahangir Embraces Shah Abbas', 'Our Lady of Berdyczow', 'Santa Maria Novella Crucifix by Giotto', 'One Nation Under CCTV', 'Forlivese school of art', 'Breton Women and Chlidren', 'Crucifix (Cross No. 20)', "Noah's Ark", 'Super Alexia', 'Man, Controller of the Universe', 'Avalokiteshvara of Chaiya', 'Seated Woman with Bent Knees', 'Flying Balloon Girl', 'Theotokos of Buchyn', 'The Archangel Michael (icon)', "Portrait of Alfonso I d'Este", 'Equestrian Statue of Niccolò da Tolentino', 'Uppspretta', 'Theotokos of Port Arthur', 'Paolo and Francesca da Rimini', 'Meadows near Rijswijk and the Schenkweg', 'Ladder of Divine Ascent', 'Sueño de una Tarde Dominical en la Alameda Central', 'Fishing Boats, Key West', 'United Nations Security Council mural', 'Les Mots écrits de New Bell', 'The Fall of Icarus', 'Tragic Prelude', "Madonna di sant'Alessio", 'Portrait of Lady Roxanda', 'Picture clock with Alster panorama', 'Angel, Still Groping', 'Astronaut Cosmonaut', 'Art Buff', 'A Palace Concert', 'The appearance of Michael the Archangel to Joshua', 'silk painting depicting a man riding a dragon', 'Woman on Her Deathbed', 'Historia de la medicina y la farmacia en Chile', "A Peace Conference at the Quai d'Orsay", 'Crucifixion', 'Crucifix', 'The concord of the state', 'Prince Khurram departs from Ajmer for his first Deccan campaign (30 October 1616)', 'Emperor Jahangir Triumphing Over Poverty', 'Mritunjoyi Mujib', 'Nativity', 'Adoration of the Kings (Damaskinos)', 'In Thee Rejoiceth', 'Jacob’s Ladder', 'The Fall of Man (Poulakis)', 'Saint Mark', 'Mary Magdalene', 'Vision of Constantine (Stavarkis)', 'Yogimatha rock painting', 'Portrait of a Gentleman', "If You Don't Mask, You Don't Get", 'Conductores de Venezuela', 'Say Their Names', 'The Last Judgment', 'At Binsey, near Oxford', 'What Our Lord Saw from the Cross', 'Bardia Mural', 'Chartist Mural', 'Theotokos Uralskaya', 'Orgosolo’s Murals', 'Landscape with Wheelbarrow', '27 Club graffiti in Tel Aviv', 'Dead Poet Carried by a Centaur', 'Our Lady of the Sign', 'The Madonna Enthroned between St. Catherine and St. Elizabeth from Hungary', 'Avenida Paulista no dia da Inauguração, 8 de Dezembro de 1891', 'Upside Down Crucifixion of Saint Andrew', 'Le Départ des poilus, août 1914', 'Self-portrait with a Blue Sketchbook', 'Fish Magic', 'América Tropical: Oprimida y Destrozada por los Imperialismos', 'Make Everything Great Again', 'The Visitation', 'The Mild Mild West', 'Christ Bearing the Cross', 'Lovejoy Columns', 'Pan American Unity', "Jean Wauquelin presenting his 'Chroniques de Hainaut' to Philip the Good", 'The Epic of American Civilization', 'Church Pew with Worshippers', 'Theotokos Samarska', 'Jahangir Preferring a Sufi Shaikh to Kings', 'The Blue Rigi', 'Early Snow on the River', 'Together we can stop AIDS', 'grande fresque de la gare de Lyon', 'hup taem', 'Lower Simcoe Street underpass murals', 'Girl with a Pierced Eardrum', 'Virgin Glykofilousa with the Akathist Hymn', 'Jahangir with a Portrait of Akbar', 'Royal Courts of Justice', 'A Māori and Pākehā man trading a crayfish', 'Virgin Glykofilousa (Karantinos)', 'Virgin and Child on Bronze', 'Catherine of Alexandria (Kornaros)', 'The Decapitation of Khan Jahan Lodi (3 February 1631)', 'The Stoning of Stephen', 'Lady the Lambovitissa', 'The Ladder of Divine Ascent', 'Ibrahim Adil Shah II hawking', 'The Birth of the Virgin Mary', 'Tree of Jesse (Victor)', 'Dormition of Theotokos', "Saint Catherine's Engagement (Klontzas)", 'Christ Pantocrator (Palladas)', "Auckland Women's Suffrage Memorial", 'The Vine of the Virgin (Tzanes)', 'Doubting Thomas (Tzanes)', 'Transfiguration and Monastic Scenes (Klontzas)', 'Triptych of the Last Judgement (Klontzas)', 'Vision of the Apocalypse (Bathas)', 'Virgin Nikopoios', 'Enthroned Saint Anne with the Virgin and Christ Child', 'The Nativity of Christ (Poulakis)', 'Saint Onuphrius (Tzanes)', 'Virgin and Child Enthroned (Romas)', 'The Holy Trinity (Romas)', 'Tribute to the Eucharist (Damaskinos)', 'Adoration of the Shepherds (Tzangarolas)', 'The Holy Towel', 'Angel Holding the Body of Christ (Kallergis)', 'Entry of Christ into Jerusalem', 'The Miracle of the Holy Belt', 'Constantine and Helen (Moskos)', 'The Archangel Michael (Poulakis)', 'Virgin of the Burning Bush (Damaskinos)', 'Saint Theodora', 'The Virgin Pantanassa', 'Jesus Hominum Salvator', 'The Deposition from the Cross (Stavrakis)', 'The Profit Jonah', 'The Vision of Constantine', 'The Dormition and Assumption of the Virgin (Moskos)', 'Icon of the Mother of God and Infant Christ (Virgin Eleousa)', 'Stay Up Late', 'Our Lady of Ferguson', 'Shearwater Cottage Murals', 'Kissing Coppers', 'Crack Is Wack', 'Yogini with a mynah bird (CBL In 11A.31)', 'The Last Judgment (Kavertzas)', 'Beheading of John the Baptist (Damaskinos)', 'Virgin of the Passion', 'The Last Judgement (Klontzas)', 'The Last Judgment Triptych (Klontzas)', 'Stoning of Saint Stephen (Damaskinos)', 'In Thee Rejoiceth (Poulakis)', 'Saint Anne with the Virgin', 'Children Under a Palm', 'Hell icon', 'Magistrate of Brussels', 'Saint Mercurius slaying Julian the Apostate (St. George church, Struga)', 'Our Lady of Solitude of Porta Vaga', 'London Colosseum', 'Landscape with Trees', 'In You Rejoices', 'Caoutchouc', 'Princes of the House of Timur', 'Marie in the garden', 'The Peace Kids (mural)', 'Worship of the Tree of Life in the Realm of Light', 'Tower', 'Madre della Consolazione', 'Co-op Mosaic, Hull', 'Woodstock Mural', 'Silent Majority', 'The Knowledge', 'Conduit', 'Gorilla in a Pink Mask', 'Forgive Us Our Trespassing', 'Self Portrait', 'History of Snow Hill', "The Ha'Penny Bridge, Dublin", 'Front Elevation for a Monument to the Unknown Soldier', 'Panorama of Persia', 'Sodom and Gomorrah Burning', 'Tommies Bathing', 'A Young Woman Reading', 'Times Square Mural', 'The History of the Old Kent Road', 'Homage to Cincinnatus', "A View of the Archbishop's Palace, Lambeth", 'Trains', 'Topolski Century', 'The Courtyard of the Old Residency in Munich', 'Shyam Vatika', 'Peatery in Drenthe', 'Skid Row City Limits Mural', 'Sutton twin towns mural', 'Sutton heritage mosaic', 'Cable Street Mural', 'Young Woman in Blue', 'The Smiling Girl', 'Icon of the Triumph of Orthodoxy', 'Tree of physiology', 'The Picador', 'Trans-Siberian Railway Panorama', 'Bear Surprise', 'Crucifixion of Christ with saints', 'Pleasure Garden', 'Jahangir Visiting the Ascetic Jadrup', 'Kurumba painting', 'Azuchi Screens', 'The Escape of a Heretic, 1559', 'mural of Dolly Parton and RuPaul', "What's So Funny About Peace, Love, and Understanding", 'The Rising Squall, Hot Wells from St Vincent’s Rock, Bristol', 'Ruins of the Abbey Saint Bertin', 'Study of a Stork', 'The History of Transportation', 'Landscape of Łódź Seen From Retkinia', 'Mural', 'Tom Cafferty', 'mural of Marcus Rashford', 'Lehighton', 'Reception of the American Loyalists by Great Britain in the Year 1783', 'Mural of Elizabeth II', 'The Passion of Sacco and Vanzetti', 'Children at Play', 'Keith Haring Mural', 'Italy Between the Arts and Sciences', 'From this moment despair ends and tactics begin', "Women's Community Cancer Project Mural", 'Transport and Human Endeavor', 'Waxwings, Cherry Blossoms, and Bamboo', 'Freedom for Humanity', 'Queens is the Future', "Valentine's Banksy", 'The Baayfalls', 'Robert Czakó Mural', 'Portrait of Saint Bartley Harris', 'Manhattan', 'I Know You Know That I Know', 'The Houston Bowery Wall', 'Historical Panorama of Alabama Agriculture', 'Events in the Life of Harold Washington', 'Ebb and Flow', 'Death Whoop', 'Brighton Belle street mural', 'Northcote Koori Mural', 'Murals of Chapel Hill', 'Mural with Blue Brushstroke', 'Missouri Wall of Fame', 'Mississippi River Tales Mural', 'Mission Dolores mural', 'Men Without Women', 'The Expedition in Pursuit of Rare Meats', 'Portrait of a Woman with Mask', 'Procession', 'Pageant of Oregon History', 'La Memoria De Nuestra Tierra (Calif. 1996)', 'Fuck the World', 'Corroboree at Newcastle', 'ONE: Union of the Senses', 'Ramesside star clocks', 'Four Seasons', 'Portland Memorial Mausoleum Mural', 'July Reflections', 'Oregon History', 'Capax Infiniti', "Annunciation, Icon of  St. Catherine's Monastery", 'Wall of Respect', 'Packy mural', 'The Tree of Knowledge', 'The Runners', 'Independence and the Opening of the West', 'Joplin at the Turn of the Century', 'Saint Joseph Seeks a Lodging in Bethlehem', 'A Journey for Peace in EDSA', 'Tri It', 'Nelson Mandela Mural', 'Poplar Rates Rebellion Mural', 'Chicago: Epoch of a Great City', "Centenary of Women's Suffrage", 'mural by Robin Corbo', 'Rivington Street Wall', 'Tronald Dump', 'The Afro-Colombian Mural: Currulao y Desplazamiento', 'Marilyn Monroe mural', 'Funeral of Sir Thomas Lawrence: A Sketch from Memory', 'Detroit Chimera Graffiti Mural', 'Untitled (Urban Wall)', 'Woman with bicycle', 'Wagner Murals', 'Vicksburg Riverfront Murals', 'Tree of Life mural', 'Thirteen Most Wanted Men', 'Theotokos of Miasena', "The Mama Ayesha's Restaurant Presidential Mural", 'The History of Ranching', 'The Bookstore Mural', 'Saint George and the Dragon', 'Rock art of the Chumash people', 'Pomona Envisions the Future', 'Pink Lady', 'Pathfinder Mural', 'Pueblo Levee Mural Project', 'Bermuda No. 2, The Schooner']

In [11]:
target_category = 'Painting'
target_concepts = whole_df[whole_df["class_label"] == target_category]["label"].tolist()
target_concept = target_concepts[21]
# target_concept = "Portsmouth Harbour"
print(target_concept)

wiki_info = fetch_wikipedia_page(target_concept, lang="en")
main_text = extract_wiki_main_text(wiki_info['text'])
print(main_text)
wiki_info

San Damiano cross
The San Damiano Cross is the large Romanesque rood cross before which St. Francis of Assisi was praying when he is said to have received the commission from the Lord to rebuild the Church.  It hangs in the Basilica of Saint Clare (Basilica di Santa Chiara) in Assisi, Italy, with a replica in its original position in the church of San Damiano nearby.  Franciscans cherish this cross as the symbol of their mission from God.
The cross is a crucifix of a type sometimes called an icon cross because in addition to the main figure of the Christ, it contains images of other saints and people related to the incident of Christ's crucifixion.  The tradition of such painted crucifixes began in the Eastern Church and possibly reached Italy via Montenegro and Croatia.

History
The San Damiano Cross was one of a number of crosses painted with similar figures during the 11th century in Umbria. The name of the painter is unknown, but it was made around the year 1100. The purpose of an icon cross was to teach the meaning of the event depicted and thereby strengthen the faith of the people. The Byzantine style was common in Italy before Cimabue and Giotto.
According to Franciscan tradition, it was while praying before this cross in the chapel of San Damiano, just outside Assisi, that Francis of Assisi received a call to rebuild the Church.
When the Poor Clares moved from San Damiano to the Basilica of Santa Chiara in 1257, they took the original San Damiano Cross with them and still guard it with great solicitude. It now hangs in the Basilica over the altar of the Chapel of the Crucifix – a reconstruction of the Church of Saint George, which was torn down to build the Basilica. The crucifix hanging over the altar of the ancient church of San Damiano is a copy. Franciscans regard this cross as a symbol of their mission to commit their lives and resources to renewing and rebuilding the Church.

Description
Jesus Christ is represented upright in full stature while the surrounding figures are smaller. The bright white of his body contrasts with the dark red and black around it and accentuates the prominence of Jesus. This representation contrasts with the regal Christ portrayed on the cross in earlier centuries and the suffering, dying, crucified Christ depicted generally throughout the Church since the beginning of the 14th century.  Above the head of Christ is the inscription in Latin: Jesus of Nazareth, King of the Jews.
The next largest figures are five witnesses of the crucifixion. On the left side are the Virgin Mary and St. John the Evangelist. On the right side are Mary Magdalene, Mary, Mother of James, and the centurion who in Matthew's Gospel account asks Christ to heal his servant, who is also depicted on the cross on the shoulder of the centurion (Matthew 8:5-13). Both Mary and Mary Magdalene have their hands placed on their cheeks to reflect extreme grief and anguish. The first four witnesses are saints and are therefore represented with halos. Their names are written beneath their pictures.
Two smaller figures are located in the corners with the witnesses. On the lower left is Longinus the traditional name of the Roman soldier who pierced the side of Jesus with a lance. He is represented here as holding the lance and looking up at Jesus. The blood running down the right arm of Jesus begins at the elbow and drips straight down and will land on the upturned face of Longinus. In the lower right is Stephaton, the traditional name for the soldier who offered Jesus the sponge soaked in vinegar wine.
Peering over the left shoulder of the centurion is a small face. A close look reveals the tops of the heads of three others beside him. This represents the centurion's son who was healed by Jesus and the rest of his family to show that "he and his whole household believed" (John 4:45-54).
Six angels are represented as marvelling over the event of the crucifixion. They are positioned at both ends of the crossbar. Their hand gestures indicate they are discussing this wondrous event of the death and calling us to marvel with them.
At the foot of the cross there is a damaged picture of six figures, two of whom are represented with halos. In accordance with the traditions of the day, these six are the patrons of Umbria: St. Damian, St. Michael, St. Rufino, St. John the Baptist, St. Peter and St. Paul.  On the top of the cross, one sees Jesus now fully clothed in his regal garments and carrying the cross as a triumphant sceptre. He is climbing out of the tomb and into the heavenly courts. Ten angels are crowded around, five of whom have their hands extended in a welcoming gesture to Jesus, who himself has his hand raised in the form of a greeting,
At the very top of the cross is the Hand of God with two fingers extended. This is to be understood as the blessing of God the Father on the sacrifice of his Son.  On the right side of the picture next to the left calf of Jesus, there is a small figure of a fowl.  Some art historians have interpreted it to be a rooster, representing the sign of Jesus' denial by Peter, mentioned in all four Gospel accounts. Other commentators see it as a peacock, a frequent symbol of immortality in Early Christian art.

{'exists': True,
 'title': 'San Damiano Cross',
 'url': 'https://en.wikipedia.org/wiki/San_Damiano_Cross',
 'summary': "The San Damiano Cross is the large Romanesque rood cross before which St. Francis of Assisi was praying when he is said to have received the commission from the Lord to rebuild the Church.  It hangs in the Basilica of Saint Clare (Basilica di Santa Chiara) in Assisi, Italy, with a replica in its original position in the church of San Damiano nearby.  Franciscans cherish this cross as the symbol of their mission from God.\nThe cross is a crucifix of a type sometimes called an icon cross because in addition to the main figure of the Christ, it contains images of other saints and people related to the incident of Christ's crucifixion.  The tradition of such painted crucifixes began in the Eastern Church and possibly reached Italy via Montenegro and Croatia.",
 'text': 'The San Damiano Cross is the large Romanesque rood cross before which St. Francis of Assisi was praying when he is said to have received the commission from the Lord to rebuild the Church.  It hangs in the Basilica of Saint Clare (Basilica di Santa Chiara) in Assisi, Italy, with a replica in its original position in the church of San Damiano nearby.  Franciscans cherish this cross as the symbol of their mission from God.\nThe cross is a crucifix of a type sometimes called an icon cross because in addition to the main figure of the Christ, it contains images of other saints and people related to the incident of Christ\'s crucifixion.  The tradition of such painted crucifixes began in the Eastern Church and possibly reached Italy via Montenegro and Croatia.\n\nHistory\nThe San Damiano Cross was one of a number of crosses painted with similar figures during the 11th century in Umbria. The name of the painter is unknown, but it was made around the year 1100. The purpose of an icon cross was to teach the meaning of the event depicted and thereby strengthen the faith of the people. The Byzantine style was common in Italy before Cimabue and Giotto.\nAccording to Franciscan tradition, it was while praying before this cross in the chapel of San Damiano, just outside Assisi, that Francis of Assisi received a call to rebuild the Church.\nWhen the Poor Clares moved from San Damiano to the Basilica of Santa Chiara in 1257, they took the original San Damiano Cross with them and still guard it with great solicitude. It now hangs in the Basilica over the altar of the Chapel of the Crucifix – a reconstruction of the Church of Saint George, which was torn down to build the Basilica. The crucifix hanging over the altar of the ancient church of San Damiano is a copy. Franciscans regard this cross as a symbol of their mission to commit their lives and resources to renewing and rebuilding the Church.\n\nDescription\nJesus Christ is represented upright in full stature while the surrounding figures are smaller. The bright white of his body contrasts with the dark red and black around it and accentuates the prominence of Jesus. This representation contrasts with the regal Christ portrayed on the cross in earlier centuries and the suffering, dying, crucified Christ depicted generally throughout the Church since the beginning of the 14th century.  Above the head of Christ is the inscription in Latin: Jesus of Nazareth, King of the Jews.\nThe next largest figures are five witnesses of the crucifixion. On the left side are the Virgin Mary and St. John the Evangelist. On the right side are Mary Magdalene, Mary, Mother of James, and the centurion who in Matthew\'s Gospel account asks Christ to heal his servant, who is also depicted on the cross on the shoulder of the centurion (Matthew 8:5-13). Both Mary and Mary Magdalene have their hands placed on their cheeks to reflect extreme grief and anguish. The first four witnesses are saints and are therefore represented with halos. Their names are written beneath their pictures.\nTwo smaller figures are located in the corners with the witnesses. On the lower left is Longinus the traditional name of the Roman soldier who pierced the side of Jesus with a lance. He is represented here as holding the lance and looking up at Jesus. The blood running down the right arm of Jesus begins at the elbow and drips straight down and will land on the upturned face of Longinus. In the lower right is Stephaton, the traditional name for the soldier who offered Jesus the sponge soaked in vinegar wine.\nPeering over the left shoulder of the centurion is a small face. A close look reveals the tops of the heads of three others beside him. This represents the centurion\'s son who was healed by Jesus and the rest of his family to show that "he and his whole household believed" (John 4:45-54).\nSix angels are represented as marvelling over the event of the crucifixion. They are positioned at both ends of the crossbar. Their hand gestures indicate they are discussing this wondrous event of the death and calling us to marvel with them.\nAt the foot of the cross there is a damaged picture of six figures, two of whom are represented with halos. In accordance with the traditions of the day, these six are the patrons of Umbria: St. Damian, St. Michael, St. Rufino, St. John the Baptist, St. Peter and St. Paul.  On the top of the cross, one sees Jesus now fully clothed in his regal garments and carrying the cross as a triumphant sceptre. He is climbing out of the tomb and into the heavenly courts. Ten angels are crowded around, five of whom have their hands extended in a welcoming gesture to Jesus, who himself has his hand raised in the form of a greeting,\nAt the very top of the cross is the Hand of God with two fingers extended. This is to be understood as the blessing of God the Father on the sacrifice of his Son.  On the right side of the picture next to the left calf of Jesus, there is a small figure of a fowl.  Some art historians have interpreted it to be a rooster, representing the sign of Jesus\' denial by Peter, mentioned in all four Gospel accounts. Other commentators see it as a peacock, a frequent symbol of immortality in Early Christian art.\n\nSee also\nFrancis of Assisi\nBasilica di Santa Chiara\nSan Damiano, Assisi\nCrucifix\nPoor Clares\nClare of Assisi\n\nSources\nThe Franciscan Vision and the Gospel of John: The San Damiano Crucifix, Francis and John, Creation and John, by Michael Guinan, Franciscan Institute Publications, 2006. ISBN 978-1-57659-204-5\nControversial Crucifix Creates Rift at Warr Acres Church, by John Estus, 2010\n\nReferences\nFurther reading\nScanlan, Michael (1983). The San Damiano Cross: An Explanation. Steubenville, Ohio: Franciscan University Press. OCLC 10409763.\n\nExternal links\n"San Damiano Cross". Franciscan Friars TOR. 2008. Archived from the original on 2009-01-22.\nFranciscan Sisters of Perpetual Adoration'}

In [12]:
# *** prompt構築 ***
prompt = gen_triplet_prompt_base.replace("<target_concept>", target_concept)
prompt = prompt.replace("<wikipedia_text>", main_text[:10000])  # wikiページ本文は10000文字までに制限 (例. "Portsmouth Harbour"の本文は文字数9498, 単語数は1538)

print(prompt)

You are given the full main text of a Wikipedia article describing a specific proper noun.

Your task is to extract factual characteristics of the target object using only the information explicitly stated or clearly implied in the provided Wikipedia text.

### Input

#### Target object
San Damiano cross

#### Wikipedia article text
The San Damiano Cross is the large Romanesque rood cross before which St. Francis of Assisi was praying when he is said to have received the commission from the Lord to rebuild the Church.  It hangs in the Basilica of Saint Clare (Basilica di Santa Chiara) in Assisi, Italy, with a replica in its original position in the church of San Damiano nearby.  Franciscans cherish this cross as the symbol of their mission from God.
The cross is a crucifix of a type sometimes called an icon cross because in addition to the main figure of the Christ, it contains images of other saints and people related to the incident of Christ's crucifixion.  The tradition of such painted crucifixes began in the Eastern Church and possibly reached Italy via Montenegro and Croatia.

History
The San Damiano Cross was one of a number of crosses painted with similar figures during the 11th century in Umbria. The name of the painter is unknown, but it was made around the year 1100. The purpose of an icon cross was to teach the meaning of the event depicted and thereby strengthen the faith of the people. The Byzantine style was common in Italy before Cimabue and Giotto.
According to Franciscan tradition, it was while praying before this cross in the chapel of San Damiano, just outside Assisi, that Francis of Assisi received a call to rebuild the Church.
When the Poor Clares moved from San Damiano to the Basilica of Santa Chiara in 1257, they took the original San Damiano Cross with them and still guard it with great solicitude. It now hangs in the Basilica over the altar of the Chapel of the Crucifix – a reconstruction of the Church of Saint George, which was torn down to build the Basilica. The crucifix hanging over the altar of the ancient church of San Damiano is a copy. Franciscans regard this cross as a symbol of their mission to commit their lives and resources to renewing and rebuilding the Church.

Description
Jesus Christ is represented upright in full stature while the surrounding figures are smaller. The bright white of his body contrasts with the dark red and black around it and accentuates the prominence of Jesus. This representation contrasts with the regal Christ portrayed on the cross in earlier centuries and the suffering, dying, crucified Christ depicted generally throughout the Church since the beginning of the 14th century.  Above the head of Christ is the inscription in Latin: Jesus of Nazareth, King of the Jews.
The next largest figures are five witnesses of the crucifixion. On the left side are the Virgin Mary and St. John the Evangelist. On the right side are Mary Magdalene, Mary, Mother of James, and the centurion who in Matthew's Gospel account asks Christ to heal his servant, who is also depicted on the cross on the shoulder of the centurion (Matthew 8:5-13). Both Mary and Mary Magdalene have their hands placed on their cheeks to reflect extreme grief and anguish. The first four witnesses are saints and are therefore represented with halos. Their names are written beneath their pictures.
Two smaller figures are located in the corners with the witnesses. On the lower left is Longinus the traditional name of the Roman soldier who pierced the side of Jesus with a lance. He is represented here as holding the lance and looking up at Jesus. The blood running down the right arm of Jesus begins at the elbow and drips straight down and will land on the upturned face of Longinus. In the lower right is Stephaton, the traditional name for the soldier who offered Jesus the sponge soaked in vinegar wine.
Peering over the left shoulder of the centurion is a small face. A close look reveals the tops of the heads of three others beside him. This represents the centurion's son who was healed by Jesus and the rest of his family to show that "he and his whole household believed" (John 4:45-54).
Six angels are represented as marvelling over the event of the crucifixion. They are positioned at both ends of the crossbar. Their hand gestures indicate they are discussing this wondrous event of the death and calling us to marvel with them.
At the foot of the cross there is a damaged picture of six figures, two of whom are represented with halos. In accordance with the traditions of the day, these six are the patrons of Umbria: St. Damian, St. Michael, St. Rufino, St. John the Baptist, St. Peter and St. Paul.  On the top of the cross, one sees Jesus now fully clothed in his regal garments and carrying the cross as a triumphant sceptre. He is climbing out of the tomb and into the heavenly courts. Ten angels are crowded around, five of whom have their hands extended in a welcoming gesture to Jesus, who himself has his hand raised in the form of a greeting,
At the very top of the cross is the Hand of God with two fingers extended. This is to be understood as the blessing of God the Father on the sacrifice of his Son.  On the right side of the picture next to the left calf of Jesus, there is a small figure of a fowl.  Some art historians have interpreted it to be a rooster, representing the sign of Jesus' denial by Peter, mentioned in all four Gospel accounts. Other commentators see it as a peacock, a frequent symbol of immortality in Early Christian art.

### Task

For the given object, generate exactly 5 sentences for each relation type, filling in the [MASK] part according to the specified format below.

### Relation list (sentence templates)

- IsA: "It is [MASK]."
- HasA: "It has [MASK]."
- HasFeatureOf: "It is characterized by [MASK]."
- UsedFor: "It is used for [MASK]."
- LocatedIn: "It is located [MASK]."
- BuiltIn: "It was built [MASK]."
- BuiltBy: "It was built by [MASK]."
- OriginatedIn: "It originated in [MASK]."
- FoundedBy: "It was founded by [MASK]."
- FoundedIn: "It was founded in [MASK]."
- CreatedBy: "It was created by [MASK]."
- CreatedIn: "It was created in [MASK]."
- DevelopedBy: "It was developed by [MASK]."
- DevelopedIn: "It was developed in [MASK]."
- DiscoveredBy: "It was discovered by [MASK]."
- DiscoveredIn: "It was discovered in [MASK]."
- InventedBy: "It was invented by [MASK]."
- InventedIn: "It was invented in [MASK]."
- PublishedIn: "It was published in [MASK]."
- WrittenBy: "It was written by [MASK]."
- ComposedBy: "It was composed by [MASK]."
- DirectedBy: "It was directed by [MASK]."
- PerformedBy: "It was performed by [MASK]."
- ManufacturedBy: "It was manufactured by [MASK]."
- ProducedBy: "It was produced by [MASK]."
- CausedBy: "It is caused by [MASK]."
- Affects: "It affects [MASK]."
- ConsistsOf: "It consists of [MASK]."
- PartOf: "It is part of [MASK]."
- MemberOf: "It is a member of [MASK]."
- BelongsTo: "It belongs to [MASK]."
- KnownFor: "It is known for [MASK]."
- AssociatedWith: "It is associated with [MASK]."
- NamedAfter: "It is named after [MASK]."
- OccurredIn: "It occurred in [MASK]."
- HeldIn: "It was held in [MASK]."
- WonBy: "It was won by [MASK]."
- About: "It is about [MASK]."
- InfluencedBy: "It was influenced by [MASK]."
- Influenced: "It influenced [MASK]."

### Extraction rules

1. Generate up to 10 sentences per relation type.
   - If 1 to 10 valid sentences can be supported by the article, return all supported sentences.
   - If the relation is not applicable or no supporting information is found in the article, return exactly one item: "unknown"
2. Every sentence must be supported by the provided Wikipedia article text.
   - Do not add information from external knowledge.
   - Do not speculate or infer beyond what the text justifies.
3. Do NOT use parentheses () for explanations.
   - If additional detail is needed, incorporate it into the main sentence.
4. Do not mention the target object’s name, aliases, or obvious references in any sentence.
   - Also avoid "this building", "this museum", etc. Use neutral wording like "It" only.
5. Avoid generic or category-wide statements.
   - Bad: "It is a famous place."
   - Bad: "It is used for various purposes."
   - Good: Statements that capture unique, document-specific properties.
6. Keep sentences short, factual, and atomic (one fact per sentence).
7. Output must strictly follow the required JSON schema.
   - Output JSON only (no markdown, no explanations).

### Output requirements

- First output the English version.
- Then output the Japanese translation with the same structure and meaning.
- Ensure each sentence conforms to the corresponding template for that relation type.

### Special rule for missing relations

If no valid sentence can be extracted for a relation, return exactly:

"RelationName": [
  "unknown"
]

### 生成

In [51]:
print(prompt)

You are given the full main text of a Wikipedia article describing a specific proper noun.

Your task is to extract factual characteristics of the target object using only the information explicitly stated or clearly implied in the provided Wikipedia text.

### Input

#### Target object
mural of Marcus Rashford

#### Wikipedia article text
In 2020, a mural of footballer Marcus Rashford by street artist Akse P19 was painted in the Withington area of Manchester, United Kingdom. The mural was created in recognition of the work Rashford did during the COVID-19 pandemic in the United Kingdom to help tackle child food poverty.
After Rashford had missed a penalty kick for England in the UEFA Euro 2020 Final in July 2021, the mural was vandalised, prompting locals to post messages of support for Rashford before its restoration.

Description
Based on a photograph by Daniel Cheetham, the painting of Marcus Rashford was completed in 2020 by street artist Akse, in collaboration with the street art project Withington Walls, to commemorate the footballer's work to reduce child hunger. The mural is a black and white portrait painting, and appears on an exterior wall of Coffee House Café on Copson Street, near where Rashford was raised in Old Moat. The mural's quote, which reads, "Take pride in knowing that your struggle will play the biggest role in your purpose", was taken from a letter published as part of a campaign with Burberry to fund youth centres.

History
Aske spoke with Rashford while completing the artwork in November 2020 and said, "I hope the mural will inspire the local community as he has inspired the whole nation with his campaign to fight child food poverty." To celebrate Black History Month in 2021, a close-up of the mural was featured on Google Street View.

Vandalism
The painting was vandalised with the words "shite in a bucket, bastard", "fuck Sancho", and "fuck Saka" after those players and Rashford failed to score in a penalty shootout for England in the UEFA Euro 2020 Final, which meant Italy won the shootout 3–2. The Mayor of Greater Manchester, Andy Burnham, described the mural defacement as a "despicable, shameful act". Ed Wellard, co-founder of Withington Walls, worked to cover the profanity immediately; residents created a collage of supportive messages, flags, and hearts across the artwork, and Akse restored the mural. On 16 July, Manchester City Council announced plans to preserve the items left at the mural following the vandalism. A representative of the council described the public's response as a "Manchester moment we will all remember and should not forget", and BT created a virtual replication of the messages named the "Wall of Hope".
A spokesperson for Greater Manchester Police (GMP) said, "While the content of the vandalism is not believed to be of a racial nature, officers are keeping an open mind as to the motive behind defacing the artwork". Hundreds of people participated in an anti-racism demonstration at the mural, leaving Rashford "lost for words". Rashford was moved by the messages of support. He shared images of the collage and tweeted, "The communities that wrapped their arms around me continue to hold me up... I can take critique of my performance all day long... but I will never apologise for who I am and where I came from." In October 2021, GMP released CCTV footage of a hooded man within the vicinity of the mural at 23:40 BST on 11 July, who they believed may be responsible for the crime.

Reception
Bradley Ormesher of The Times described the mural as "impressive" and "a real tourist attraction".

### Task

For the given object, generate exactly 5 sentences for each relation type, filling in the [MASK] part according to the specified format below.

### Relation list (sentence templates)

- IsA: "It is [MASK]."
- HasA: "It has [MASK]."
- HasFeatureOf: "It is characterized by [MASK]."
- UsedFor: "It is used for [MASK]."
- LocatedIn: "It is located [MASK]."
- BuiltIn: "It was built [MASK]."
- BuiltBy: "It was built by [MASK]."
- OriginatedIn: "It originated in [MASK]."
- FoundedBy: "It was founded by [MASK]."
- FoundedIn: "It was founded in [MASK]."
- CreatedBy: "It was created by [MASK]."
- CreatedIn: "It was created in [MASK]."
- DevelopedBy: "It was developed by [MASK]."
- DevelopedIn: "It was developed in [MASK]."
- DiscoveredBy: "It was discovered by [MASK]."
- DiscoveredIn: "It was discovered in [MASK]."
- InventedBy: "It was invented by [MASK]."
- InventedIn: "It was invented in [MASK]."
- PublishedIn: "It was published in [MASK]."
- WrittenBy: "It was written by [MASK]."
- ComposedBy: "It was composed by [MASK]."
- DirectedBy: "It was directed by [MASK]."
- PerformedBy: "It was performed by [MASK]."
- ManufacturedBy: "It was manufactured by [MASK]."
- ProducedBy: "It was produced by [MASK]."
- CausedBy: "It is caused by [MASK]."
- Affects: "It affects [MASK]."
- ConsistsOf: "It consists of [MASK]."
- PartOf: "It is part of [MASK]."
- MemberOf: "It is a member of [MASK]."
- BelongsTo: "It belongs to [MASK]."
- KnownFor: "It is known for [MASK]."
- AssociatedWith: "It is associated with [MASK]."
- NamedAfter: "It is named after [MASK]."
- OccurredIn: "It occurred in [MASK]."
- HeldIn: "It was held in [MASK]."
- WonBy: "It was won by [MASK]."
- About: "It is about [MASK]."
- InfluencedBy: "It was influenced by [MASK]."
- Influenced: "It influenced [MASK]."

### Extraction rules

1. Generate up to 10 sentences per relation type.
   - If 1 to 10 valid sentences can be supported by the article, return all supported sentences.
   - If the relation is not applicable or no supporting information is found in the article, return exactly one item: "unknown"
2. Every sentence must be supported by the provided Wikipedia article text.
   - Do not add information from external knowledge.
   - Do not speculate or infer beyond what the text justifies.
3. Do NOT use parentheses () for explanations.
   - If additional detail is needed, incorporate it into the main sentence.
4. Do not mention the target object’s name, aliases, or obvious references in any sentence.
   - Also avoid "this building", "this museum", etc. Use neutral wording like "It" only.
5. Avoid generic or category-wide statements.
   - Bad: "It is a famous place."
   - Bad: "It is used for various purposes."
   - Good: Statements that capture unique, document-specific properties.
6. Keep sentences short, factual, and atomic (one fact per sentence).
7. Output must strictly follow the required JSON schema.
   - Output JSON only (no markdown, no explanations).

### Output requirements

- First output the English version.
- Then output the Japanese translation with the same structure and meaning.
- Ensure each sentence conforms to the corresponding template for that relation type.

### Special rule for missing relations

If no valid sentence can be extracted for a relation, return exactly:

"RelationName": [
  "unknown"
]

In [54]:
model = "gemini-2.5-flash-lite"
response = client.models.generate_content(
    model=model,
    contents=prompt,
    config=schema
)

In [55]:
import json

record = {
    "response_id": response.response_id,
    "model_version": response.model_version,
    "text": response.text,
    "parsed": response.parsed,
    "usage_metadata": {
        "prompt_token_count": response.usage_metadata.prompt_token_count,
        "candidates_token_count": response.usage_metadata.candidates_token_count,
        "total_token_count": response.usage_metadata.total_token_count,
    },
}


filename = f"{target_concept.replace(' ', '_')}.json"
with open(os.path.join(gen_result_savedir, filename), "w", encoding="utf-8") as f:
    # f.write(json.dumps(record, ensure_ascii=False) + "\n") # jsonl形式で1fileに追加し続ける場合 ('w'ではなく'a'にする必要あり)
    json.dump(record, f, ensure_ascii=False, indent=4)

In [ ]:
# お試しで1カテゴリ分を生成する
# num = 10
target_category = 'Painting'
target_concepts = whole_df[whole_df["class_label"] == target_category]["label"].tolist()
for target_concept in target_concepts:
    print(target_concept)
    if target_concept in generated_concepts:
        print(f"Concept '{target_concept}' ALREADY has GENERATED factual feature sentences. Skipping generation.")
        continue
    # wikipageのテキストをapiで取得する
    wiki_info = fetch_wikipedia_page(target_concept, lang="en")
    if wiki_info["exists"] == False:
        print(f"Wikipedia page for concept '{target_concept}' DOES NOT exist. Skipping generation.")
        continue
    main_text = extract_wiki_main_text(wiki_info['text'])
    print(main_text)
    
    if len(main_text.split()) < wiki_word_num_threshold:
        # もし十分な情報量(本文の文字数)がない場合は、生成をスキップする
        print(f"Concept '{target_concept}' has insufficient Wikipedia text ({len(main_text.split())} words). Skipping generation.")
        continue

### 生成2: 1カテゴリ分だけ生成

In [ ]:
def gen_with_google_genai_api(prompt, schema, temperature=0.2, topP=0.8, model="gemini-2.5-flash-lite", max_retries=1):
    """Google GenAI APIを呼び出して、指定したスキーマに沿った応答を生成する。
    Args:
        prompt (str): プロンプトのテキスト。
        schema (dict): 生成された応答が従うべきJSONスキーマ。
        temperature (float): 生成時の温度パラメータ。デフォルトは0.2。
        topP (float): 生成時のtopPパラメータ。デフォルトは0.8。
        model (str): 使用するモデル名。デフォルトは"gemini-2.5-flash-lite"。
        max_retries (int): API呼び出しの最大リトライ回数。デフォルトは1。
    Returns:
        response をそのまま返す
        ×dict: 生成された応答がスキーマに従っている場合はその応答を辞書形式で返す。スキーマに従っていない場合はNoneを返す。
    """
    schema["temperature"] = temperature  # スキーマに温度パラメータを追加
    schema["topP"] = topP  # スキーマにtopPパラメータを追加

    # *** Gemini で生成 ***
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model=model,
                contents=prompt,
                config=schema
            )
        except Exception as e:
            print(f"Attempt {attempt + 1} failed with error: {e}")
            if attempt == max_retries - 1:
                raise e
            else:
                continue
        # APIからの応答を取得
        return response
        # generated_text = response.output_text.strip()
        # # print(f"【generated_text】\n{generated_text}")
        # return generated_text
    return None


def gen_with_openai_api(prompt, schema, temperature, topP, model="gpt-5-mini", max_retries=1):
    """OpenAI APIを呼び出して、指定したスキーマに沿った応答を生成する。
    Args:
        prompt (str): プロンプトのテキスト。
        schema (dict): 生成された応答が従うべきJSONスキーマ。
        temperature (float): 生成時の温度パラメータ。デフォルトは0.2。
        topP (float): 生成時のtopPパラメータ。デフォルトは0.8。
        model (str): 使用するモデル名。デフォルトは"gpt-5-mini"。
        max_retries (int): API呼び出しの最大リトライ回数。デフォルトは1。
    Returns:
        response をそのまま返す
        ×dict: 生成された応答がスキーマに従っている場合はその応答を辞書形式で返す。スキーマに従っていない場合はNoneを返す。
    """

    # *** GPT5で生成 ***
    for attempt in range(max_retries):
        try:
            response = client.responses.create(
                model=model,
                input=prompt,
                text={
                    "format": schema
                },
            )
        except Exception as e:
            print(f"Attempt {attempt + 1} failed with error: {e}")
            if attempt == max_retries - 1:
                raise e
            else:
                continue
        # APIからの応答を取得
        return response
        # generated_text = response.output_text.strip()
        # # print(f"【generated_text】\n{generated_text}")
        # return generated_text
    return None

In [59]:


def gen_and_save_wiki_fact_extraction_for_concept(
        target_concept, 
        feat_num_threshold, 
        wiki_word_num_threshold, 
        prompt_template, 
        schema, 
        gen_result_savedir, 
        model="gemini-2.5-flash-lite", 
        temperature=0.2, 
        topP=0.8,
        max_retries=1
    ):
    """
    Generate factual feature sentences for a given concept using Wikipedia information.
    Args:
        target_concept (str): The concept for which to generate factual features.
        feat_num_threshold (int): The minimum number of valid features required for successful generation.
        wiki_word_num_threshold (int): The minimum number of words required in the Wikipedia text for successful generation.
        prompt_template (str): The template for the generation prompt, containing placeholders for the target concept and Wikipedia text.
        schema (dict): The JSON schema that the generated response should adhere to.
        gen_result_savedir (str): The directory where the generated results should be saved.
        model (str): The model to use for generation. Default is "gemini-2.5-flash-lite".
        temperature (float): The temperature parameter for generation. Default is 0.2.
        topP (float): The topP parameter for generation. Default is 0.8.
        max_retries (int): The maximum number of retries for API calls. Default is 1.
    Returns:
        bool: True if generation is successful (i.e., the number of valid features meets the threshold), False otherwise.

    もし生成された特徴の数(unkonwn除く)がfeat_num_threshold未満であっても、生成結果自体は保存する。
    """
    
    # wikipageのテキストをapiで取得する
    wiki_info = fetch_wikipedia_page(target_concept, lang="en")
    if wiki_info["exists"] == False:
        print(f"Wikipedia page for concept '{target_concept}' DOES NOT exist. Skipping generation.")
        return False
    main_text = extract_wiki_main_text(wiki_info['text'])
    # print(main_text)
    
    if len(main_text.split()) < wiki_word_num_threshold:
        # もし十分な情報量(本文の文字数)がない場合は、生成をスキップする
        print(f"Concept '{target_concept}' has insufficient Wikipedia text ({len(main_text.split())} words). Skipping generation.")
        return False

    # prompt構築
    prompt = prompt_template.replace("<target_concept>", target_concept)
    prompt = prompt.replace("<wikipedia_text>", main_text[:10000])  # wikiページ本文は10000文字までに制限 (例. "Portsmouth Harbour"の本文は文字数9498, 単語数は1538)

    # 生成
    if model.startswith("gemini"):
        response = gen_with_google_genai_api(prompt, schema, temperature, topP, model, max_retries)
        if response is not None:
            record = {
                "response_id": response.response_id,
                "model_version": response.model_version,
                "text": response.text,
                "parsed": response.parsed,
                "usage_metadata": {
                    "prompt_token_count": response.usage_metadata.prompt_token_count,
                    "candidates_token_count": response.usage_metadata.candidates_token_count,
                    "total_token_count": response.usage_metadata.total_token_count,
                },
            }
            # 生成された(有効な)特徴数が feat_num_threshold 以上であれば生成成功とみなす
            total_features = sum(response.parsed['english'].values(), [])
            total_features = [feat for feat in total_features if feat.lower() != "unknown"] # featが unknown や Unknown などの意味のない特徴であれば削除する
            if len(total_features) >= feat_num_threshold:
                gen_succeeded = True
            else:
                gen_succeeded = False
        else:
            record = {
                "error": "Failed to generate a valid response after maximum retries.",
                "prompt": prompt,
                "schema": schema,
                "model": model,
                "max_retries": max_retries,
            }
            gen_succeeded = False

    elif model.startswith("gpt"):
        response = gen_with_openai_api(prompt, schema, temperature, topP, model, max_retries)
        pass # [WIP] ここではまだgpt-5-miniでの生成は試さないため、実装は保留中
    else:
        raise ValueError(f"Unsupported model: {model}")
    
    # 保存
    filename = f"{target_concept.replace(' ', '_')}.json"
    with open(os.path.join(gen_result_savedir, filename), "w", encoding="utf-8") as f:
        # f.write(json.dumps(record, ensure_ascii=False) + "\n") # jsonl形式で1fileに追加し続ける場合 ('w'ではなく'a'にする必要あり)
        json.dump(record, f, ensure_ascii=False, indent=4)

    return gen_succeeded

In [61]:
# 生成済みのconceptについては生成をスキップするため、事前に確認しておく
print("Checking already generated concepts...")
generated_concepts = []
for filename in os.listdir(gen_result_savedir):
    if filename.endswith(".json"):
        concept = filename.split('.json')[0]  # 拡張子を除いた部分を取得
        concept = concept.replace('_', ' ')  # ファイル名のアンダースコアをスペースに変換
        generated_concepts.append(concept)

generated_concepts

Checking already generated concepts...

['Silent Majority',
 'The History of Mexico',
 'Ustyug Annunciation',
 'mural of Marcus Rashford',
 "Noah's Ark",
 'Dormition of Theotokos',
 'Sutton twin towns mural',
 'Leda and the Swan',
 'Adoration of the Kings']

In [ ]:
import random
random.seed(42)  # 再現性のためにシードを固定

target_category = 'Painting'
target_concepts = whole_df[whole_df["class_label"] == target_category]["label"].tolist()
target_concepts = random.sample(target_concepts, k=len(target_concepts))


model = "gemini-2.5-flash-lite"
max_retries = 1
feat_num_threshold = 60 # 1概念あたりで、生成された特徴の数がこの数以上であれば生成成功とみなす
wiki_word_num_threshold = 500 # 十分な情報量のあるwikipageに対してのみ生成を行うための、wikipageの本文の単語数の閾値
propnoun_num_for_new_concept = 50
propnoun_num_for_init_vec = 100
temperature = 0.2
topP = 0.8


# 生成済みのconceptについては生成をスキップするため、事前に確認しておく
print("Checking already generated concepts...")
generated_concepts = []
for filename in os.listdir(gen_result_savedir):
    if filename.endswith(".json"):
        concept = filename.split('.json')[0]  # 拡張子を除いた部分を取得
        concept = concept.replace('_', ' ')  # ファイル名のアンダースコアをスペースに変換
        generated_concepts.append(concept)


# 生成ループ
gen_success_count = 0   # 生成成功した概念の数 (生成された特徴の数が feat_num_threshold 以上であった概念の数)
total_gen_count = 0     # 生成を試みた概念の総数 (生成成功・失敗に関わらず)
for target_concept in target_concepts:
    if target_concept in generated_concepts:
        print(f"Concept '{target_concept}' ALREADY has GENERATED factual feature sentences. Skipping generation.")
        continue
    if gen_success_count >= propnoun_num_for_new_concept:
        print(f"REACHED the target number of successfully generated concepts ({propnoun_num_for_new_concept}). Stopping generation for this category.")
        break


    total_gen_count += 1
    print(f"Generating factual feature sentences for concept: {target_concept}")
    gen_succeeded = gen_and_save_wiki_fact_extraction_for_concept(
        target_concept=target_concept,
        feat_num_threshold=feat_num_threshold,
        wiki_word_num_threshold=wiki_word_num_threshold,
        prompt_template=gen_triplet_prompt_base,
        schema=schema,
        gen_result_savedir=gen_result_savedir,
        model=model,
        temperature=temperature,
        topP=topP,
        max_retries=max_retries
    )
    print(f"\tGeneration result for {target_concept}: {gen_succeeded}")
    gen_success_count += gen_succeeded

print(f"{gen_success_count}/{total_gen_count} concepts successfully generated with factual feature sentences for the category {target_category}.")

Checking already generated concepts...
Concept 'mural of Marcus Rashford' ALREADY has GENERATED factual feature sentences. Skipping generation.
Generating factual feature sentences for concept: Boy Cutting Grass with a Sickle
Concept 'Boy Cutting Grass with a Sickle' has insufficient Wikipedia text (24 words). Skipping generation.
	Generation result for Boy Cutting Grass with a Sickle: False
Concept 'Leda and the Swan' ALREADY has GENERATED factual feature sentences. Skipping generation.
Generating factual feature sentences for concept: Independence and the Opening of the West
Concept 'Independence and the Opening of the West' has insufficient Wikipedia text (134 words). Skipping generation.
	Generation result for Independence and the Opening of the West: False
Generating factual feature sentences for concept: Art Buff
Concept 'Art Buff' has insufficient Wikipedia text (206 words). Skipping generation.
	Generation result for Art Buff: False
Generating factual feature sentences for concept: Theotokos of Port Arthur
Concept 'Theotokos of Port Arthur' has insufficient Wikipedia text (334 words). Skipping generation.
	Generation result for Theotokos of Port Arthur: False
Concept 'Noah's Ark' ALREADY has GENERATED factual feature sentences. Skipping generation.
Concept 'Adoration of the Kings' ALREADY has GENERATED factual feature sentences. Skipping generation.
Generating factual feature sentences for concept: The Tree of Knowledge
Concept 'The Tree of Knowledge' has insufficient Wikipedia text (218 words). Skipping generation.
	Generation result for The Tree of Knowledge: False
Generating factual feature sentences for concept: Nicopeia
Concept 'Nicopeia' has insufficient Wikipedia text (195 words). Skipping generation.
	Generation result for Nicopeia: False
Generating factual feature sentences for concept: I Know You Know That I Know
Concept 'I Know You Know That I Know' has insufficient Wikipedia text (23 words). Skipping generation.
	Generation result for I Know You Know That I Know: False
Generating factual feature sentences for concept: Pink Lady
Concept 'Pink Lady' has insufficient Wikipedia text (276 words). Skipping generation.
	Generation result for Pink Lady: False
Concept 'Silent Majority' ALREADY has GENERATED factual feature sentences. Skipping generation.
Concept 'Ustyug Annunciation' ALREADY has GENERATED factual feature sentences. Skipping generation.
Concept 'Sutton twin towns mural' ALREADY has GENERATED factual feature sentences. Skipping generation.
Concept 'Dormition of Theotokos' ALREADY has GENERATED factual feature sentences. Skipping generation.
Generating factual feature sentences for concept: Blue Dancers
Concept 'Blue Dancers' has insufficient Wikipedia text (50 words). Skipping generation.
	Generation result for Blue Dancers: False
Generating factual feature sentences for concept: Wall of Love
Concept 'Wall of Love' has insufficient Wikipedia text (236 words). Skipping generation.
	Generation result for Wall of Love: False
Concept 'The History of Mexico' ALREADY has GENERATED factual feature sentences. Skipping generation.
Generating factual feature sentences for concept: Forlivese school of art
Concept 'Forlivese school of art' has insufficient Wikipedia text (55 words). Skipping generation.
	Generation result for Forlivese school of art: False
Generating factual feature sentences for concept: Flying Balloon Girl
Concept 'Flying Balloon Girl' has insufficient Wikipedia text (223 words). Skipping generation.
	Generation result for Flying Balloon Girl: False
Generating factual feature sentences for concept: The Last Judgment Triptych (Klontzas)
Wikipedia page for concept 'The Last Judgment Triptych (Klontzas)' DOES NOT exist. Skipping generation.
	Generation result for The Last Judgment Triptych (Klontzas): False
Generating factual feature sentences for concept: Tree of physiology
Concept 'Tree of physiology' has insufficient Wikipedia text (378 words). Skipping generation.
	Generation result for Tree of physiology: False
Generating factual feature sentences for concept: Panagia Portaitissa
	Generation result for Panagia Portaitissa: True
Generating factual feature sentences for concept: Front Elevation for a Monument to the Unknown Soldier
Concept 'Front Elevation for a Monument to the Unknown Soldier' has insufficient Wikipedia text (52 words). Skipping generation.
	Generation result for Front Elevation for a Monument to the Unknown Soldier: False
Generating factual feature sentences for concept: Presentation at the Temple
	Generation result for Presentation at the Temple: True
Generating factual feature sentences for concept: Corroboree at Newcastle
Concept 'Corroboree at Newcastle' has insufficient Wikipedia text (241 words). Skipping generation.
	Generation result for Corroboree at Newcastle: False
Generating factual feature sentences for concept: Children at Play
Concept 'Children at Play' has insufficient Wikipedia text (257 words). Skipping generation.
	Generation result for Children at Play: False
Generating factual feature sentences for concept: Men Without Women
Concept 'Men Without Women' has insufficient Wikipedia text (92 words). Skipping generation.
	Generation result for Men Without Women: False
Generating factual feature sentences for concept: Tree of Life mural
Wikipedia page for concept 'Tree of Life mural' DOES NOT exist. Skipping generation.
	Generation result for Tree of Life mural: False
Generating factual feature sentences for concept: The Birth of the Virgin Mary
Wikipedia page for concept 'The Birth of the Virgin Mary' DOES NOT exist. Skipping generation.
	Generation result for The Birth of the Virgin Mary: False
Generating factual feature sentences for concept: Breton Women and Chlidren
Wikipedia page for concept 'Breton Women and Chlidren' DOES NOT exist. Skipping generation.
	Generation result for Breton Women and Chlidren: False
Generating factual feature sentences for concept: Virgin and Child Enthroned (Romas)
	Generation result for Virgin and Child Enthroned (Romas): True
Generating factual feature sentences for concept: Skid Row City Limits Mural
Concept 'Skid Row City Limits Mural' has insufficient Wikipedia text (320 words). Skipping generation.
	Generation result for Skid Row City Limits Mural: False
Generating factual feature sentences for concept: The appearance of Michael the Archangel to Joshua
Wikipedia page for concept 'The appearance of Michael the Archangel to Joshua' DOES NOT exist. Skipping generation.
	Generation result for The appearance of Michael the Archangel to Joshua: False
Generating factual feature sentences for concept: Rock Paintings of Hua Mountain
Concept 'Rock Paintings of Hua Mountain' has insufficient Wikipedia text (358 words). Skipping generation.
	Generation result for Rock Paintings of Hua Mountain: False
Generating factual feature sentences for concept: Venus and the Three Graces Presenting Gifts to Giovanna degli Albizzi
Wikipedia page for concept 'Venus and the Three Graces Presenting Gifts to Giovanna degli Albizzi' DOES NOT exist. Skipping generation.
	Generation result for Venus and the Three Graces Presenting Gifts to Giovanna degli Albizzi: False
Generating factual feature sentences for concept: Mississippi River Tales Mural
Concept 'Mississippi River Tales Mural' has insufficient Wikipedia text (147 words). Skipping generation.
	Generation result for Mississippi River Tales Mural: False
Generating factual feature sentences for concept: Woman with bicycle
Concept 'Woman with bicycle' has insufficient Wikipedia text (144 words). Skipping generation.
	Generation result for Woman with bicycle: False
Generating factual feature sentences for concept: 27 Club graffiti in Tel Aviv
	Generation result for 27 Club graffiti in Tel Aviv: False
Generating factual feature sentences for concept: The History of Ranching
Wikipedia page for concept 'The History of Ranching' DOES NOT exist. Skipping generation.
	Generation result for The History of Ranching: False
Generating factual feature sentences for concept: Half-Length Nude with Hat
Wikipedia page for concept 'Half-Length Nude with Hat' DOES NOT exist. Skipping generation.
	Generation result for Half-Length Nude with Hat: False
Generating factual feature sentences for concept: One Nation Under CCTV
Concept 'One Nation Under CCTV' has insufficient Wikipedia text (87 words). Skipping generation.
	Generation result for One Nation Under CCTV: False
Generating factual feature sentences for concept: Orgosolo’s Murals
Wikipedia page for concept 'Orgosolo’s Murals' DOES NOT exist. Skipping generation.
	Generation result for Orgosolo’s Murals: False
Generating factual feature sentences for concept: The Mama Ayesha's Restaurant Presidential Mural
	Generation result for The Mama Ayesha's Restaurant Presidential Mural: True
Generating factual feature sentences for concept: Funeral of Sir Thomas Lawrence: A Sketch from Memory
Wikipedia page for concept 'Funeral of Sir Thomas Lawrence: A Sketch from Memory' DOES NOT exist. Skipping generation.
	Generation result for Funeral of Sir Thomas Lawrence: A Sketch from Memory: False
Generating factual feature sentences for concept: Jahangir Preferring a Sufi Shaikh to Kings
	Generation result for Jahangir Preferring a Sufi Shaikh to Kings: True
Generating factual feature sentences for concept: Theotokos Fyodorovskaya
	Generation result for Theotokos Fyodorovskaya: True
Generating factual feature sentences for concept: América Tropical: Oprimida y Destrozada por los Imperialismos
Concept 'América Tropical: Oprimida y Destrozada por los Imperialismos' has insufficient Wikipedia text (470 words). Skipping generation.
	Generation result for América Tropical: Oprimida y Destrozada por los Imperialismos: False
Generating factual feature sentences for concept: Our Lady of the Sign
	Generation result for Our Lady of the Sign: True
Generating factual feature sentences for concept: The Picador
Wikipedia page for concept 'The Picador' DOES NOT exist. Skipping generation.
	Generation result for The Picador: False
Generating factual feature sentences for concept: Madonna di sant'Alessio
	Generation result for Madonna di sant'Alessio: True
Generating factual feature sentences for concept: Cestello Annunciation
Concept 'Cestello Annunciation' has insufficient Wikipedia text (201 words). Skipping generation.
	Generation result for Cestello Annunciation: False
Generating factual feature sentences for concept: Entry of Christ into Jerusalem
	Generation result for Entry of Christ into Jerusalem: True
Generating factual feature sentences for concept: Worship of the Tree of Life in the Realm of Light
Wikipedia page for concept 'Worship of the Tree of Life in the Realm of Light' DOES NOT exist. Skipping generation.
	Generation result for Worship of the Tree of Life in the Realm of Light: False
Generating factual feature sentences for concept: Sant'Ambrogio Altarpiece
Wikipedia page for concept 'Sant'Ambrogio Altarpiece' DOES NOT exist. Skipping generation.
	Generation result for Sant'Ambrogio Altarpiece: False
Generating factual feature sentences for concept: Theotokos Samarska
Concept 'Theotokos Samarska' has insufficient Wikipedia text (98 words). Skipping generation.
	Generation result for Theotokos Samarska: False
Generating factual feature sentences for concept: Blachernitissa
	Generation result for Blachernitissa: True
Generating factual feature sentences for concept: Gorilla in a Pink Mask
Concept 'Gorilla in a Pink Mask' has insufficient Wikipedia text (271 words). Skipping generation.
	Generation result for Gorilla in a Pink Mask: False
Generating factual feature sentences for concept: Prince Khurram departs from Ajmer for his first Deccan campaign (30 October 1616)
Wikipedia page for concept 'Prince Khurram departs from Ajmer for his first Deccan campaign (30 October 1616)' DOES NOT exist. Skipping generation.
	Generation result for Prince Khurram departs from Ajmer for his first Deccan campaign (30 October 1616): False
Generating factual feature sentences for concept: Ruins of the Abbey Saint Bertin
Concept 'Ruins of the Abbey Saint Bertin' has insufficient Wikipedia text (130 words). Skipping generation.
	Generation result for Ruins of the Abbey Saint Bertin: False
Generating factual feature sentences for concept: Azuchi Screens
	Generation result for Azuchi Screens: False
Generating factual feature sentences for concept: The Visitation
Concept 'The Visitation' has insufficient Wikipedia text (86 words). Skipping generation.
	Generation result for The Visitation: False
Generating factual feature sentences for concept: A View of the Archbishop's Palace, Lambeth
Concept 'A View of the Archbishop's Palace, Lambeth' has insufficient Wikipedia text (136 words). Skipping generation.
	Generation result for A View of the Archbishop's Palace, Lambeth: False
Generating factual feature sentences for concept: Ancha icon
	Generation result for Ancha icon: True
Generating factual feature sentences for concept: Manoppello Image
	Generation result for Manoppello Image: True
Generating factual feature sentences for concept: The Chocolate Girl
	Generation result for The Chocolate Girl: True
Generating factual feature sentences for concept: Waxwings, Cherry Blossoms, and Bamboo
Concept 'Waxwings, Cherry Blossoms, and Bamboo' has insufficient Wikipedia text (66 words). Skipping generation.
	Generation result for Waxwings, Cherry Blossoms, and Bamboo: False
Generating factual feature sentences for concept: Man, Controller of the Universe
	Generation result for Man, Controller of the Universe: True
Generating factual feature sentences for concept: Crucifix
	Generation result for Crucifix: True
Generating factual feature sentences for concept: Murals of Chapel Hill
	Generation result for Murals of Chapel Hill: True
Generating factual feature sentences for concept: The Afro-Colombian Mural: Currulao y Desplazamiento
Concept 'The Afro-Colombian Mural: Currulao y Desplazamiento' has insufficient Wikipedia text (276 words). Skipping generation.
	Generation result for The Afro-Colombian Mural: Currulao y Desplazamiento: False
Generating factual feature sentences for concept: Presencia de America Latina
	Generation result for Presencia de America Latina: True
Generating factual feature sentences for concept: Fuck the World
Concept 'Fuck the World' has insufficient Wikipedia text (135 words). Skipping generation.
	Generation result for Fuck the World: False
Generating factual feature sentences for concept: July Reflections
Concept 'July Reflections' has insufficient Wikipedia text (25 words). Skipping generation.
	Generation result for July Reflections: False
Generating factual feature sentences for concept: Adoration of the Shepherds (Tzangarolas)
Concept 'Adoration of the Shepherds (Tzangarolas)' has insufficient Wikipedia text (497 words). Skipping generation.
	Generation result for Adoration of the Shepherds (Tzangarolas): False
Generating factual feature sentences for concept: Mural
	Generation result for Mural: True
Generating factual feature sentences for concept: The Mild Mild West
Concept 'The Mild Mild West' has insufficient Wikipedia text (235 words). Skipping generation.
	Generation result for The Mild Mild West: False
Generating factual feature sentences for concept: Khakhuli triptych
Concept 'Khakhuli triptych' has insufficient Wikipedia text (444 words). Skipping generation.
	Generation result for Khakhuli triptych: False
Generating factual feature sentences for concept: Pan American Unity
	Generation result for Pan American Unity: True
Generating factual feature sentences for concept: Self-portrait with a Blue Sketchbook
Concept 'Self-portrait with a Blue Sketchbook' has insufficient Wikipedia text (47 words). Skipping generation.
	Generation result for Self-portrait with a Blue Sketchbook: False
Generating factual feature sentences for concept: Emperor Jahangir Embraces Shah Abbas
Wikipedia page for concept 'Emperor Jahangir Embraces Shah Abbas' DOES NOT exist. Skipping generation.
	Generation result for Emperor Jahangir Embraces Shah Abbas: False
Generating factual feature sentences for concept: Portrait of Lady Roxanda
Concept 'Portrait of Lady Roxanda' has insufficient Wikipedia text (149 words). Skipping generation.
	Generation result for Portrait of Lady Roxanda: False
Generating factual feature sentences for concept: The Annunciation
	Generation result for The Annunciation: True
Generating factual feature sentences for concept: Bear Surprise
Concept 'Bear Surprise' has insufficient Wikipedia text (134 words). Skipping generation.
	Generation result for Bear Surprise: False
Generating factual feature sentences for concept: From this moment despair ends and tactics begin
Concept 'From this moment despair ends and tactics begin' has insufficient Wikipedia text (125 words). Skipping generation.
	Generation result for From this moment despair ends and tactics begin: False
Generating factual feature sentences for concept: Altarpiece of the church of the monastery of Santo Domingo el Antiguo
Wikipedia page for concept 'Altarpiece of the church of the monastery of Santo Domingo el Antiguo' DOES NOT exist. Skipping generation.
	Generation result for Altarpiece of the church of the monastery of Santo Domingo el Antiguo: False
Generating factual feature sentences for concept: The Peace Kids (mural)
	Generation result for The Peace Kids (mural): True
Generating factual feature sentences for concept: Rock art of the Chumash people
	Generation result for Rock art of the Chumash people: True
Generating factual feature sentences for concept: Keith Haring Mural
Concept 'Keith Haring Mural' has insufficient Wikipedia text (391 words). Skipping generation.
	Generation result for Keith Haring Mural: False
Generating factual feature sentences for concept: The Miracle of the Holy Belt
	Generation result for The Miracle of the Holy Belt: True
Generating factual feature sentences for concept: Portrait of Saint Bartley Harris
	Generation result for Portrait of Saint Bartley Harris: True
Generating factual feature sentences for concept: Angel, Still Groping
Concept 'Angel, Still Groping' has insufficient Wikipedia text (161 words). Skipping generation.
	Generation result for Angel, Still Groping: False
Generating factual feature sentences for concept: History of Snow Hill
	Generation result for History of Snow Hill: False
Generating factual feature sentences for concept: Joplin at the Turn of the Century
Concept 'Joplin at the Turn of the Century' has insufficient Wikipedia text (187 words). Skipping generation.
	Generation result for Joplin at the Turn of the Century: False
Generating factual feature sentences for concept: The Last Judgment
	Generation result for The Last Judgment: True
Generating factual feature sentences for concept: Great Piece of Turf
Concept 'Great Piece of Turf' has insufficient Wikipedia text (478 words). Skipping generation.
	Generation result for Great Piece of Turf: False
Generating factual feature sentences for concept: Avalokiteshvara of Chaiya
	Generation result for Avalokiteshvara of Chaiya: True
Generating factual feature sentences for concept: Untitled (Urban Wall)
	Generation result for Untitled (Urban Wall): False
Generating factual feature sentences for concept: Yogimatha rock painting
Concept 'Yogimatha rock painting' has insufficient Wikipedia text (391 words). Skipping generation.
	Generation result for Yogimatha rock painting: False
Generating factual feature sentences for concept: A Māori and Pākehā man trading a crayfish
Concept 'A Māori and Pākehā man trading a crayfish' has insufficient Wikipedia text (89 words). Skipping generation.
	Generation result for A Māori and Pākehā man trading a crayfish: False
Generating factual feature sentences for concept: Picture clock with Alster panorama
Concept 'Picture clock with Alster panorama' has insufficient Wikipedia text (354 words). Skipping generation.

In [66]:
target_category

'Painting'

In [63]:
gen_success_count

50

In [65]:
len(os.listdir(gen_result_savedir))

70